let a = document.getElementById("first")
console.log(a.getAttribute("class"))
console.log(a.hasAttribute("class"))
console.log(a.hasAttribute("style"))
// a.setAttribute("hidden",true)
a.setAttribute("class","hey adding class")
// a.removeAttribute("class")
console.log(a.dataset)
console.log(a.dataset.game)
console.log(a.dataset.player)